# 鱼获收集时长
# 单位 秒 在 1 ~ 10秒 获得1条鱼
fish-get-time: "10~20"

# 工作需要的鱼饵数量
working-food: 1


# 鱼列表
# 可以放置自定义物品
fish-list:
  - "minecraft:cod"
  - "minecraft:cod"
  - "minecraft:cod"
  - "minecraft:cod"
  - "0:0"
  - "0:0"
  - "minecraft.salmon"
  - "minecraft.salmon"
  - "minecraft.salmon"
  - "minecraft.salmon"
  - "0:0"
  - "0:0"
  - "minecraft:pufferfish"
  - "minecraft:pufferfish"
  - "minecraft:pufferfish"
  - "minecraft:pufferfish"
  - "0:0"
  - "301:0"
  - "minecraft:tropical_fish"
  - "minecraft:tropical_fish"
  - "minecraft:tropical_fish"
  - "minecraft:tropical_fish"
  - "0:0"
  - "0:0"
  - "280:0"
  - "280:0"
  - "301:0"
  - "280:0"
  - "280:0"
  - "minecraft:cod"
  - "minecraft:cod"
  - "minecraft:cod"
  - "minecraft:cod"
  - "0:0"
  - "0:0"
  - "minecraft.salmon"
  - "minecraft.salmon"
  - "minecraft.salmon"
  - "minecraft.salmon"
  - "0:0"
  - "0:0"
  - "301:20"
  - "minecraft:pufferfish"
  - "0:0"
  - "0:0"
  - "minecraft:tropical_fish"
  - "0:0"
  - "0:0"
